# Generated by Django 4.1.1 on 2022-09-13 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itens',
            options={'verbose_name_plural': 'Itens'},
        ),
        migrations.AlterModelOptions(
            name='itensclass',
            options={'verbose_name_plural': 'Itens-Classe'},
        ),
        migrations.AlterModelOptions(
            name='rpgrace',
            options={'verbose_name_plural': 'Races'},
        ),
        migrations.AlterModelOptions(
            name='skills',
            options={'verbose_name_plural': 'Skills'},
        ),
    ]
