# Generated by Django 4.1.1 on 2022-09-15 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_itens_options_alter_itensclass_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpgclass',
            name='constitution',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
