# Generated by Django 4.1.1 on 2022-09-15 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_rpgrace_life_alter_rpgclass_charism_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itens',
            old_name='damage',
            new_name='definition',
        ),
        migrations.RenameField(
            model_name='itens',
            old_name='description',
            new_name='name',
        ),
    ]
