# Generated by Django 4.1.1 on 2022-09-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_damage_itens_definition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itens',
            name='definition',
            field=models.CharField(max_length=200),
        ),
    ]
