# Generated by Django 4.1.1 on 2022-09-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_itens_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itens',
            name='definition',
            field=models.CharField(max_length=300),
        ),
    ]
