# Generated by Django 4.1.1 on 2022-09-26 14:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_itens_definition'),
    ]

    operations = [
        migrations.CreateModel(
            name='character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
            ],
        ),
        migrations.AddField(
            model_name='rpgclass',
            name='itens',
            field=models.ManyToManyField(related_name='rpgclass', to='core.itens'),
        ),
        migrations.AlterField(
            model_name='rpgrace',
            name='charism',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='rpgrace',
            name='constitution',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='rpgrace',
            name='dexterity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='rpgrace',
            name='intelligence',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='rpgrace',
            name='strength',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='rpgrace',
            name='wisdom',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.DeleteModel(
            name='itensclass',
        ),
        migrations.AddField(
            model_name='character',
            name='rpgclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='character', to='core.rpgclass'),
        ),
        migrations.AddField(
            model_name='character',
            name='rpgrace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='character', to='core.rpgrace'),
        ),
    ]
