# Generated by Django 4.1.1 on 2022-09-26 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media', '__first__'),
        ('core', '0008_character_rpgclass_itens_alter_rpgrace_charism_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='img',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='media.image'),
        ),
    ]
